### ISSUE TITLE
Can‘t run live analysis using  leelaz

### ISSUE THREAD

**Issue by jun63cn** [pnprog/goreviewpartner#21] opened 2018-02-09 23:08 UTC
![20180210065944](https://user-images.githubusercontent.com/30382868/36054417-36365c36-0e31-11e8-9dcb-7a50c009d399.png)
![20180210070126](https://user-images.githubusercontent.com/30382868/36054418-366be77a-0e31-11e8-89e3-8c7c02862b8a.png)

**Comment by pnprog** [comment] 2018-02-11 09:02
Hi! Thanks for reporting the issue,

May I asked 3 questions:
* what version of LeelaZero you are running? if possible, may I have the command line used to run it?
* Did you download and used the **goreviewpartner-v0.10-Leela-Zero.zip** from (http://ns1297.imingo.net/) or did you download and run the sources from github?
* The run analysis is not working, could you confirm the standard analysis is not working as well?

**Comment by jun63cn** [comment] 2018-02-11 10:40
the version of leelazero I used is 0.11 next branches windows 7 x64  build
d: \leela-zero\leelaz.exe  --gtp --noponder -t 2 
I  download and run the sources from github  and both live and standard analysis are not working as well.  leela gtp no problem.
 Thank you,

**Comment by pnprog** [comment] 2018-02-11 12:39
I don't see what is causing this issue. It seems that you LeelaZero standard error output is different from mine. Moreover, the analysis of move 1 appears to be done properly, but not move 2, this is strange.

In order for me to understand, could you modify the **leela_zero_analysis.py** file as follow:

1/ go to [line 259](https://github.com/pnprog/goreviewpartner/blob/1a618cb3e73fad8cef317539b03599303162debb/leela_zero_analysis.py#L259)
2/ the line 259 looks like this `#log(err_line)`
3/ remove the first character `#` so that the line 259 now looks like this: `log(err_line)`
4/ then run again the analysis and let's look at what you get


Below is what could be expected, I am interested to see what happens on you side:
```
==============
move 1
leela Zero play black
  C4 ->       3 (V: 50.14%) (N:  3.97%) PV: C4 Q4 D17

  Q3 ->       3 (V: 50.20%) (N:  4.29%) PV: Q3 Q16 C4

 C16 ->       3 (V: 50.29%) (N:  3.99%) PV: C16 D4 Q17

  R4 ->       3 (V: 50.51%) (N:  4.23%) PV: R4 D4 Q17

 D17 ->       3 (V: 50.56%) (N:  4.55%) PV: D17 Q16 C4

 Q17 ->       3 (V: 50.56%) (N:  4.48%) PV: Q17 D16 R4

  D3 ->       4 (V: 50.74%) (N:  4.96%) PV: D3 Q16 R4

 R16 ->       4 (V: 50.74%) (N:  4.49%) PV: R16 Q4 D17

 D16 ->       9 (V: 49.79%) (N: 12.18%) PV: D16 Q4 R16 D4

  Q4 ->      12 (V: 49.66%) (N: 16.17%) PV: Q4 D16 D3 R16

 Q16 ->      13 (V: 49.91%) (N: 16.08%) PV: Q16 D4 D17 R4

  D4 ->      14 (V: 49.69%) (N: 17.37%) PV: D4 Q16 Q3 C16

Number of alternative sequences: 12
```

Thanks for your help!

**Comment by jun63cn** [comment] 2018-02-12 02:26
![Uploading 1.png…]()
![Uploading 2.png…]()
![Uploading 3.png…]()
![Uploading 4.png…]()



[leela-zero.zip](https://github.com/pnprog/goreviewpartner/files/1715154/leela-zero.zip)

**Comment by pnprog** [comment] 2018-02-12 11:24
Ok! thanks a lot for your help, I see where the problem is coming from. Well, in fact, I can't really explain what is it but, during the analysis, GRP checks LeelaZ's output for line containing `->` then parses them to extract analysis value (moves, number of playout, winrate, sequence...). Example:

`C4 ->       3 (V: 50.14%) (N:  3.97%) PV: C4 Q4 D17`

So now, for some reason, on your particular setting, one can see there is also a line containing this token at the very end:

`update_root, 9374671 -> 950315 nodes (10.1% reused)`

And so, GRP misinterprets it and fails when trying to extract the usual values from it.

I don't know the meaning of that line, and why it's not appearing on my computer (I will ask on the Leea Zeo project) but at least, I think I can patch it now.

**Comment by pnprog** [comment] 2018-02-12 11:53
I just pushed a small code modification that should solve this issue. Can you have a try and let me know?

**Comment by jun63cn** [comment] 2018-02-12 12:29
It's works.  thanks for your work.

**Comment by pnprog** [comment] 2018-02-12 14:01
I am closing this now, the discussion has moved here: https://github.com/gcp/leela-zero/issues/864

**Closed by pnprog** 2018-02-12 14:01 UTC
